package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	"github.com/Brime/gatorcli/internal/config"
	"github.com/Brime/gatorcli/internal/database"
	_ "github.com/lib/pq" // Driver for PostgreSQL database connections
)

func main() {
	// 1. Load user configuration from the JSON config file
	conf, err := config.Read()
	if err != nil {
		log.Fatal(err)
	}

	// 2. Establish a connection pool to the PostgreSQL database
	dbURL := conf.DbUrl
	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		log.Fatal(err)
	}

	// 3. Initialize the database query layer (generated by sqlc)
	dbQueries := database.New(db)

	// 4. Set up the application state with shared dependencies
	s := state{
		db:  dbQueries,
		cfg: &conf,
	}

	// 5. Initialize the command router and register handlers
	cmds := commands{
		handlers: make(map[string]func(*state, command) error),
	}

	// General commands (available to any user)
	cmds.register("login", handlerLogin)
	cmds.register("register", handlerRegister)
	cmds.register("reset", handlerReset)
	cmds.register("users", handlerUsers)
	cmds.register("agg", handlerAgg)

	// Protected commands (require the user to be logged in via middleware)
	cmds.register("addfeed", middlewareLoggedIn(handlerAddFeed))
	cmds.register("feeds", handlerFeeds)
	cmds.register("follow", middlewareLoggedIn(handlerFollow))
	cmds.register("following", middlewareLoggedIn(handlerFollowing))
	cmds.register("unfollow", middlewareLoggedIn(handlerUnfollow))
	cmds.register("browse", middlewareLoggedIn(handlerBrowse))

	// 6. Validate CLI arguments (we need at least a command name, e.g., 'gator login')
	if len(os.Args) < 2 {
		fmt.Println("invalid command")
		os.Exit(1)
	}

	// 7. Parse the command name and arguments from CLI inputs
	cmd := command{
		name: os.Args[1],
		args: os.Args[2:],
	}

	// 8. Execute the requested command
	err = cmds.run(&s, cmd)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
